# Site settings
name: Alisa’s Blog
email: Alisaljn@126.com
author: Alisa
baseurl: ""
description: 在研途中遇见更好的自己~
meta_description: Alisa;个人博客;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: katherine001
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
gems: [jekyll-paginate]

